package com.example.util

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val language: AppLanguage,

    // Header & Tabs
    val appName: String,
    val settingsTitle: String,
    val tabSettingsAndAccount: String,
    val tabSpeedTest: String,
    val tabLogs: String,
    val close: String,

    // Account & Status
    val userGreetingDefault: String,
    val activeGmbAccount: String,
    val statusConnected: String,
    val statusDisconnected: String,
    val logoutButton: String,
    val logoutDialogTitle: String,
    val logoutDialogMessage: String,
    val confirmLogout: String,
    val cancel: String,

    // Language Section
    val languageSectionTitle: String,
    val languageSectionSubtitle: String,
    val activeBadge: String,
    val langFaTitle: String,
    val langFaDesc: String,
    val langEnTitle: String,
    val langEnDesc: String,
    val langArIqTitle: String,
    val langArIqDesc: String,

    // Theme Section
    val themeSectionTitle: String,
    val themeSectionSubtitle: String,
    val themeLightTitle: String,
    val themeDarkTitle: String,
    val themeSystemTitle: String,
    val themeLightBadge: String,
    val themeDarkBadge: String,
    val themeSystemBadge: String,

    // Quick Tools & Shortcuts
    val speedTestShortcutTitle: String,
    val speedTestShortcutDesc: String,
    val logsShortcutTitle: String,
    val logsShortcutDesc: String,

    // Support Section
    val supportSectionTitle: String,
    val supportSectionSubtitle: String,
    val telegramSupportTitle: String,
    val telegramSupportDesc: String,
    val telegramChannelTitle: String,
    val telegramChannelDesc: String,
    val officialWebsiteTitle: String,
    val officialWebsiteDesc: String,
    val copiedToClipboard: String,

    // Main Dashboard
    val serverStatusTitle: String,
    val statusEncryptedActive: String,
    val statusConnectingToServer: String,
    val statusNetworkLostWaiting: String,
    val statusReconnectingAttempt: (Int) -> String,
    val statusSubscriptionExpired: String,
    val statusConnectionError: String,
    val statusTapToConnect: String,

    val buttonStart: String,
    val buttonConnected: String,
    val buttonConnecting: String,
    val buttonRetrying: String,
    val buttonLocked: String,
    val buttonError: String,

    val durationLabel: String,
    val downloadSpeedLabel: String,
    val uploadSpeedLabel: String,
    val remainingDaysLabel: String,
    val totalTrafficLabel: String,
    val renewOrStore: String,
    val subscriptionExpiredTitle: String,
    val subscriptionExpiredNotice: String,

    // Operators & Protocols
    val operatorIrancellTag: String,
    val operatorRightelTag: String,
    val operatorMciTag: String,
    val operatorWifiTag: String,

    // Speed Test
    val runSpeedTestButton: String,
    val cancelSpeedTestButton: String,
    val pingLabel: String,
    val jitterLabel: String,
    val downloadLabel: String,
    val uploadLabel: String,
    val qualityGradeLabel: String,

    // Logs
    val clearLogsButton: String,
    val copyLogsButton: String,
    val logsCopiedToast: String,
    val noLogsAvailable: String,

    // Additional Settings & Dialog Strings
    val copyLabel: String,
    val helpTipsTitle: String,
    val helpTipsBody: String,
    val speedTestUnit: String,
    val speedTestPing: String,
    val speedTestJitter: String,
    val speedTestTunnelStatus: String,
    val speedTestStop: String,
    val speedTestRetest: String,
    val speedTestStart: String,
    val searchLogsPlaceholder: String,
    val filterAll: String,
    val filterErrors: String,
    val filterSuccess: String,
    val filterInfo: String,
    val noLogsFound: String,
    val privacyNotice: String,
    val clearLogsTitle: String,
    val clearLogsConfirm: String,
    val yesDelete: String,
    val logsClearedToast: String,
    val openUrlErrorToast: (String) -> String,

    // MainScreen Strings
    val store: String,
    val renew: String,
    val fastRenew: String,
    val subscriptionExpiredNoticeCard: String,
    val subscriptionExpiredTouchToRenew: String,
    val subscriptionExpiringDays: (Int) -> String,
    val tunnelConnectingServer: String,
    val tunnelInternetDisconnectedWaiting: String,
    val tunnelReconnectingAttempt: (Int) -> String,
    val tunnelReconnecting: String,
    val tunnelErrorTapToRetry: String,
    val tunnelReadyTapToStart: String,
    val standbyWaitingForInternet: String,
    val smartRecoveryActive: (Int) -> String,
    val connectionDuration: String,
    val downloadLabelLong: String,
    val uploadLabelLong: String,
    val usernameCard: String,
    val noAccount: String,
    val activeSubscription: String,
    val expired: String,
    val remainingTime: String,
    val daysUnit: (Int) -> String,
    val zeroDays: String,
    val urgentRenewNeeded: String,
    val validSubscription: String,
    val endingSoon: String,
    val finishDateSolar: String,
    val periodEnd: String,
    val jalaliCalendar: String,
    val trafficUsage: String,
    val trafficLimit: (String) -> String,
    val unlimitedTraffic: String,
    val errorOpeningBrowser: String,
    val browserErrorWithUrl: (String) -> String,

    // Battery Card
    val batteryCardTitle: String,
    val batteryCardSubtitle: String,
    val batteryCardDesc: String,
    val batteryCardFix: String,
    val batteryCardCpu: String,
    val batteryCardAndroid: String,

    // Modal & Voucher Redeem
    val subscriptionExpiredTitleModal: String,
    val storeAndRenewTitleModal: String,
    val subscriptionExpiredDescModal: String,
    val subscriptionActiveDescModal: String,
    val usernameFieldLabel: String,
    val finishDateFieldLabel: String,
    val accountStatusFieldLabel: String,
    val daysRemainingUnit: (Int) -> String,
    val renewWithLicenseCode: String,
    val enterStore: String,
    val recheckAccountStatus: String,
    val renewWithVoucherDialogTitle: String,
    val enterVoucherPrompt: String,
    val activeAccountLabel: String,
    val voucherExamplePlaceholder: String,
    val clearField: String,
    val pasteFromClipboard: String,
    val dontHaveLicensePrompt: String,
    val validatingLicenseOnServer: String,
    val creditAddedDays: (Int) -> String,
    val trafficAddedGB: (Int) -> String,
    val confirmAndClose: String,
    val renewingProgress: String,
    val confirmAndRenew: String,
    val cancelAction: String,
    val logoutDialogTitle: String,
    val logoutDialogMessage: String,
    val updateTitle: String,
    val updateForceLabel: String,
    val updateVersionLabel: (String) -> String,
    val updateDesc: String,
    val updateChangelogTitle: String,
    val updateDownloadingProgress: String,
    val updateDirectInstall: String,
    val updateRemindLater: String,

    // LoginScreen Strings
    val loginTitle: String,
    val loginSubtitle: String,
    val loginUsernameLabel: String,
    val loginUsernamePlaceholder: String,
    val loginPasswordLabel: String,
    val loginPasswordPlaceholder: String,
    val loginRememberMe: String,
    val loginValidating: String,
    val loginButtonSubmit: String,
    val loginOrDivider: String,
    val loginNeedAccountHint: String,
    val loginBuySubscription: String,
    val loginPoweredBy: String,
    val loginValidationEmpty: String,

    // PurchaseScreen Strings
    val purchaseTitle: String,
    val purchaseSubtitle: String,
    val back: String,
    val guestUser: String,
    val remainingCreditLabel: String,
    val remainingTrafficLabel: String,
    val expiryDateLabel: String,
    val unlimitedLabel: String,
    val officialWebsiteCard: String,
    val buyVoucherTitle: String,
    val buyVoucherDesc: String,
    val goToSiteAndBuy: String,
    val websiteCopiedToast: String,
    val copyWebsiteUrl: String,
    val instantRechargeCard: String,
    val submitLicenseCard: String,
    val enterVoucherInBox: String,
    val licenseInputPlaceholder: String,
    val communicatingWithServer: String,
    val addedDaysToSubscription: (Int) -> String,
    val addedVolumeToAccount: (Int) -> String,
    val checkingAndApplying: String,
    val confirmAndRenewSubscription: String,
    val purchaseStepsTitle: String,
    val step1Number: String,
    val step1Title: String,
    val step1Desc: String,
    val step2Number: String,
    val step2Title: String,
    val step2Desc: String,
    val step3Number: String,
    val step3Title: String,
    val step3Desc: String
) {
    companion object {
        val fa = AppStrings(
            language = AppLanguage.FA,
            appName = "GMB NET",
            settingsTitle = "تنظیمات و امکانات",
            tabSettingsAndAccount = "تنظیمات و حساب",
            tabSpeedTest = "تست سرعت",
            tabLogs = "لاگ‌ها",
            close = "بستن",

            userGreetingDefault = "کاربر گرامی",
            activeGmbAccount = "حساب کاربری فعال GMB",
            statusConnected = "اتصال فعال",
            statusDisconnected = "قطع",
            logoutButton = "خروج از حساب کاربری",
            logoutDialogTitle = "خروج از حساب",
            logoutDialogMessage = "آیا مطمئن هستید که می‌خواهید از حساب کاربری خود خارج شوید؟",
            confirmLogout = "خروج",
            cancel = "انصراف",

            languageSectionTitle = "زبان برنامه (Language)",
            languageSectionSubtitle = "زبان مورد نظر خود را برای محیط کاربری انتخاب کنید:",
            activeBadge = "فعال",
            langFaTitle = "فارسی",
            langFaDesc = "زبان پیش‌فرض",
            langEnTitle = "English",
            langEnDesc = "انگلیسی",
            langArIqTitle = "العربية (العراق)",
            langArIqDesc = "عربی عراق",

            themeSectionTitle = "حالت شب (دارک مود)",
            themeSectionSubtitle = "ظاهر و پوسته نمایشی برنامه را مطابق سلیقه خود انتخاب کنید:",
            themeLightTitle = "لایت مود",
            themeDarkTitle = "دارک مود",
            themeSystemTitle = "اتوماتیک",
            themeLightBadge = "لایت مود فعال",
            themeDarkBadge = "دارک مود فعال",
            themeSystemBadge = "اتوماتیک (سیستم)",

            speedTestShortcutTitle = "تست سرعت",
            speedTestShortcutDesc = "پینگ و پهنای باند",
            logsShortcutTitle = "لاگ‌های سیستم",
            logsShortcutDesc = "گزارشات اتصال امن",

            supportSectionTitle = "ارتباط با پشتیبانی",
            supportSectionSubtitle = "پاسخگویی و راهنمایی سریع",
            telegramSupportTitle = "پشتیبانی تلگرام",
            telegramSupportDesc = "پاسخگویی سریع ۲۴ ساعته",
            telegramChannelTitle = "کانال رسمی",
            telegramChannelDesc = "اطلاع‌رسانی وضعیت سرورها و اخبار",
            officialWebsiteTitle = "وبسایت رسمی",
            officialWebsiteDesc = "خرید و تمدید اشتراک",
            copiedToClipboard = "کپی شد",

            serverStatusTitle = "وضعیت سرور",
            statusEncryptedActive = "اتصال با رمزگذاری سرتاسری فعال است",
            statusConnectingToServer = "در حال برقراری ارتباط با سرور امن...",
            statusNetworkLostWaiting = "اینترنت قطع شد - در انتظار اتصال به شبکه...",
            statusReconnectingAttempt = { attempt -> "قطع ارتباط - در حال اتصال مجدد خودکار (تلاش $attempt)..." },
            statusSubscriptionExpired = "اشتراک منقضی شده است (اتصال مسدود)",
            statusConnectionError = "خطا در اتصال به سرور",
            statusTapToConnect = "برای برقراری اتصال امن کلیک کنید",

            buttonStart = "شروع",
            buttonConnected = "متصل",
            buttonConnecting = "در حال اتصال",
            buttonRetrying = "تلاش مجدد",
            buttonLocked = "قفل",
            buttonError = "خطا",

            durationLabel = "زمان اتصال",
            downloadSpeedLabel = "دریافت (دانلود)",
            uploadSpeedLabel = "ارسال (آپلود)",
            remainingDaysLabel = "روز باقیمانده",
            totalTrafficLabel = "ترافیک کل",
            renewOrStore = "تمدید و خرید",
            subscriptionExpiredTitle = "اشتراک شما منقضی شده است",
            subscriptionExpiredNotice = "جهت اتصال مجدد به اینترنت آزاد، لطفاً اشتراک خود را تمدید فرمایید.",

            operatorIrancellTag = "ایرانسل (MTN) • پروتکل پرسرعت VMess",
            operatorRightelTag = "رایتل (Rightel) • پروتکل پرسرعت VMess",
            operatorMciTag = "همراه اول (MCI) • پروتکل امن SSH",
            operatorWifiTag = "وای‌فای / سایر • پروتکل امن SSH",

            runSpeedTestButton = "شروع سنجش سرعت اینترنت",
            cancelSpeedTestButton = "توقف آزمایش",
            pingLabel = "پینگ (Latency)",
            jitterLabel = "نوسان (Jitter)",
            downloadLabel = "دانلود",
            uploadLabel = "آپلود",
            qualityGradeLabel = "کیفیت شبکه",

            clearLogsButton = "پاک‌سازی گزارشات",
            copyLogsButton = "کپی لاگ‌ها",
            logsCopiedToast = "گزارشات با موفقیت کپی شدند",
            noLogsAvailable = "هنوز گزارشی ثبت نشده است",

            copyLabel = "کپی",
            helpTipsTitle = "راهنمای اتصال پایدار",
            helpTipsBody = "• در صورت بروز کندی، ابتدا وضعیت اینترنت اپراتور خود را بررسی نمایید.\n• در زمان تغییر شبکه از Wi-Fi به همراه (و برعکس)، VPN به طور خودکار بازاتصال خواهد شد.\n• کلیه آدرس‌ها و اطلاعات سرور برای امنیت کامل کاربران رمزنگاری شده است.",
            speedTestUnit = "Mbps",
            speedTestPing = "پینگ (Ping)",
            speedTestJitter = "جیتر (Jitter)",
            speedTestTunnelStatus = "وضعیت تونل",
            speedTestStop = "توقف تست سرعت",
            speedTestRetest = "تست مجدد سرعت",
            speedTestStart = "شروع تست سرعت",
            searchLogsPlaceholder = "جستجو در لاگ‌ها...",
            filterAll = "همه",
            filterErrors = "خطاها",
            filterSuccess = "موفق",
            filterInfo = "اطلاعات",
            noLogsFound = "هیچ لاگی یافت نشد.",
            privacyNotice = "کلیه آدرس‌ها و اطلاعات حساس سرور برای حفظ حریم خصوصی فیلتر شده‌اند",
            clearLogsTitle = "پاک‌سازی تاریخچه لاگ‌ها",
            clearLogsConfirm = "آیا اطمینان دارید که می‌خواهید تمام لاگ‌های ذخیره‌شده پاک شوند؟",
            yesDelete = "بله، پاک شود",
            logsClearedToast = "لاگ‌ها با موفقیت پاک شدند",
            openUrlErrorToast = { url -> "خطا در باز کردن لینک: $url" },

            // MainScreen Strings
            store = "فروشگاه",
            renew = "تمدید",
            fastRenew = "تمدید سریع",
            subscriptionExpiredNoticeCard = "اشتراک شما به پایان رسیده است",
            subscriptionExpiredTouchToRenew = "اتصال مسدود است • لمس جهت تمدید آنلاین",
            subscriptionExpiringDays = { days -> "تنها $days روز از اشتراک شما باقی مانده است" },
            tunnelConnectingServer = "در حال برقراری ارتباط با سرور امن...",
            tunnelInternetDisconnectedWaiting = "اینترنت قطع شد - در انتظار اتصال به شبکه...",
            tunnelReconnectingAttempt = { attempt -> "در حال اتصال مجدد خودکار (تلاش $attempt)..." },
            tunnelReconnecting = "در حال برقراری مجدد تونل ارتباطی...",
            tunnelErrorTapToRetry = "خطا در برقراری اتصال - لمس جهت تلاش مجدد",
            tunnelReadyTapToStart = "آماده اتصال - برای شروع لمس کنید",
            standbyWaitingForInternet = "سیستم آماده‌باش: منتظر برقراری اینترنت",
            smartRecoveryActive = { attempt -> "بازیابی هوشمند فعال است (تلاش $attempt)" },
            connectionDuration = "مدت اتصال:",
            downloadLabelLong = "دریافت (دانلود)",
            uploadLabelLong = "ارسال (آپلود)",
            usernameCard = "نام کاربری",
            noAccount = "بدون حساب",
            activeSubscription = "اشتراک فعال",
            expired = "منقضی شده",
            remainingTime = "زمان باقی‌مانده",
            daysUnit = { days -> "$days روز" },
            zeroDays = "۰ روز",
            urgentRenewNeeded = "نیازمند تمدید فوری",
            validSubscription = "اعتبار معتبر",
            endingSoon = "رو به پایان",
            finishDateSolar = "تاریخ پایان (شمسی)",
            periodEnd = "پایان دوره",
            jalaliCalendar = "تقویم جلالی",
            trafficUsage = "حجم مصرفی",
            trafficLimit = { limit -> "سقف: $limit" },
            unlimitedTraffic = "ترافیک نامحدود",
            errorOpeningBrowser = "خطا در باز کردن مرورگر",
            browserErrorWithUrl = { url -> "خطا در باز کردن مرورگر: $url" },

            // Battery Card
            batteryCardTitle = "رفع محدودیت باتری",
            batteryCardSubtitle = "پایداری پس‌زمینه و مصرف بهینه",
            batteryCardDesc = "جلوگیری از قطع اتصال هنگام خاموشی صفحه",
            batteryCardFix = "MTU ۱۴۰۰ ضدافت‌سرعت",
            batteryCardCpu = "پردازش کم‌مصرف CPU",
            batteryCardAndroid = "سازگار با اندروید ۷ تا ۱۵",

            // Modal & Voucher Redeem
            subscriptionExpiredTitleModal = "پایان اعتبار اشتراک",
            storeAndRenewTitleModal = "فروشگاه و تمدید اشتراک",
            subscriptionExpiredDescModal = "اعتبار اشتراک شما به پایان رسیده است. جهت تمدید با کد لایسنس یا خرید اشتراک از فروشگاه اقدام فرمایید.",
            subscriptionActiveDescModal = "جهت خرید اشتراک یا تمدید با کد لایسنس، گزینه مورد نظر را انتخاب کنید.",
            usernameFieldLabel = "نام کاربری:",
            finishDateFieldLabel = "تاریخ پایان:",
            accountStatusFieldLabel = "وضعیت حساب:",
            daysRemainingUnit = { days -> "$days روز باقی‌مانده" },
            renewWithLicenseCode = "تمدید با کد لایسنس",
            enterStore = "ورود به فروشگاه",
            recheckAccountStatus = "استعلام مجدد وضعیت حساب",
            renewWithVoucherDialogTitle = "تمدید با کد لایسنس / ووچر",
            enterVoucherPrompt = "کد لایسنس یا ووچر خریداری‌شده را جهت تمدید اعتبار اشتراک در کادر زیر وارد نمایید:",
            activeAccountLabel = "حساب کاربری فعال:",
            voucherExamplePlaceholder = "مثال: GMB-VOUCHER-XXXX",
            clearField = "پاک کردن",
            pasteFromClipboard = "جای‌گذاری از کلیپ‌بورد",
            dontHaveLicensePrompt = "کد لایسنس ندارید؟ خرید آنی از فروشگاه",
            validatingLicenseOnServer = "در حال ارسال و اعتبارسنجی لایسنس در سرور...",
            creditAddedDays = { days -> "اعتبار اضافه شده: $days روز" },
            trafficAddedGB = { gb -> "حجم اضافه شده: $gb گیگابایت" },
            confirmAndClose = "تایید و بستن",
            renewingProgress = "در حال تمدید...",
            confirmAndRenew = "تایید و تمدید اشتراک",
            cancelAction = "انصراف",
            logoutDialogTitle = "خروج از حساب کاربری",
            logoutDialogMessage = "آیا اطمینان دارید که می‌خواهید از حساب خارج شوید؟ در صورت خروج، اتصال شما قطع خواهد شد.",
            updateTitle = "بروزرسانی GMB NET",
            updateForceLabel = "بروزرسانی الزامی",
            updateVersionLabel = { v -> "نسخه $v" },
            updateDesc = "نسخه جدیدی از برنامه با بهینه‌سازی سرعت و پایداری منتشر شد.",
            updateChangelogTitle = "تغییرات این نسخه:",
            updateDownloadingProgress = "در حال دانلود فایل نصب APK...",
            updateDirectInstall = "دانلود و نصب مستقیم",
            updateRemindLater = "بعداً یادآوری کن",

            // LoginScreen Strings
            loginTitle = "ورود به اپلیکیشن",
            loginSubtitle = "جهت اتصال ایمن، مشخصات اشتراک خود را وارد نمایید",
            loginUsernameLabel = "نام کاربری",
            loginUsernamePlaceholder = "نام کاربری اشتراک...",
            loginPasswordLabel = "کلمه عبور",
            loginPasswordPlaceholder = "رمز عبور اختصاصی...",
            loginRememberMe = "مرا به خاطر بسپار",
            loginValidating = "در حال اعتبارسنجی و ورود...",
            loginButtonSubmit = "ورود به حساب کاربری",
            loginOrDivider = "یا",
            loginNeedAccountHint = "جهت دریافت نام کاربری و رمز عبور ابتدا اشتراک تهیه کنید",
            loginBuySubscription = "خرید اشتراک",
            loginPoweredBy = "قدرت گرفته توسط گمبرون نت",
            loginValidationEmpty = "لطفاً نام کاربری و کلمه عبور را وارد فرمایید",

            // PurchaseScreen Strings
            purchaseTitle = "تمدید و خرید با کد لایسنس",
            purchaseSubtitle = "فعال‌سازی آنی اعتبار و حجم با ووچر",
            back = "بازگشت",
            guestUser = "کاربر میهمان",
            remainingCreditLabel = "اعتبار باقیمانده",
            remainingTrafficLabel = "حجم باقیمانده",
            expiryDateLabel = "تاریخ انقضا",
            unlimitedLabel = "نامحدود",
            officialWebsiteCard = "وب‌سایت رسمی",
            buyVoucherTitle = "خرید کد ووچر و لایسنس",
            buyVoucherDesc = "برای خرید کد لایسنس یا ووچر تمدید، لطفاً به سایت رسمی ما مراجعه فرمایید. پس از خرید فوری از سایت، کد در اختیار شما قرار می‌گیرد و می‌توانید در کادر زیر ثبت کنید.",
            goToSiteAndBuy = "ورود به سایت gmb-net.ir و خرید کد ووچر",
            websiteCopiedToast = "آدرس سایت gmb-net.ir کپی شد",
            copyWebsiteUrl = "کپی آدرس سایت",
            instantRechargeCard = "تمدید و شارژ آنی",
            submitLicenseCard = "ثبت کد لایسنس و فعال‌سازی",
            enterVoucherInBox = "کد ووچر یا لایسنس خریداری‌شده را در کادر زیر وارد یا جای‌گذاری کنید تا اشتراک شما فورا تمدید شود:",
            licenseInputPlaceholder = "کد لایسنس (مثال: GMB-VOUCHER-XXXX)",
            communicatingWithServer = "در حال ارتباط با سرور و تایید لایسنس...",
            addedDaysToSubscription = { days -> "+$days روز به اشتراک شما اضافه شد" },
            addedVolumeToAccount = { gb -> "+$gb گیگابایت ترافیک به حسابتان اضافه شد" },
            checkingAndApplying = "در حال بررسی و اعمال...",
            confirmAndRenewSubscription = "تایید و تمدید اشتراک",
            purchaseStepsTitle = "مراحل خرید و تمدید:",
            step1Number = "۱",
            step1Title = "ورود به وب‌سایت gmb-net.ir",
            step1Desc = "از طریق دکمه بالا وارد سایت شده و پلن مورد نظر خود را انتخاب و خریداری نمایید.",
            step2Number = "۲",
            step2Title = "دریافت کد لایسنس / ووچر",
            step2Desc = "پس از پرداخت، کد اختصاصی به صورت فوری در سایت و ایمیل در اختیارتان قرار می‌گیرد.",
            step3Number = "۳",
            step3Title = "ثبت کد در برنامه",
            step3Desc = "کد را در کادر بالا درج کرده و دکمه «تایید و تمدید اشتراک» را لمس کنید تا بلافاصله حسابتان فعال شود."
        )

        val en = AppStrings(
            language = AppLanguage.EN,
            appName = "GMB NET",
            settingsTitle = "Settings & Features",
            tabSettingsAndAccount = "Settings & Account",
            tabSpeedTest = "Speed Test",
            tabLogs = "Logs",
            close = "Close",

            userGreetingDefault = "Dear User",
            activeGmbAccount = "Active GMB Account",
            statusConnected = "Connected",
            statusDisconnected = "Disconnected",
            logoutButton = "Log Out of Account",
            logoutDialogTitle = "Log Out",
            logoutDialogMessage = "Are you sure you want to log out of your account?",
            confirmLogout = "Log Out",
            cancel = "Cancel",

            languageSectionTitle = "App Language",
            languageSectionSubtitle = "Choose your preferred language for the interface:",
            activeBadge = "Active",
            langFaTitle = "فارسی",
            langFaDesc = "Persian",
            langEnTitle = "English",
            langEnDesc = "US / International",
            langArIqTitle = "العربية (العراق)",
            langArIqDesc = "Iraqi Arabic",

            themeSectionTitle = "Theme & Appearance",
            themeSectionSubtitle = "Customize the app visual theme to your preference:",
            themeLightTitle = "Light Mode",
            themeDarkTitle = "Dark Mode",
            themeSystemTitle = "Automatic",
            themeLightBadge = "Light Active",
            themeDarkBadge = "Dark Active",
            themeSystemBadge = "System Auto",

            speedTestShortcutTitle = "Speed Test",
            speedTestShortcutDesc = "Ping & Bandwidth",
            logsShortcutTitle = "System Logs",
            logsShortcutDesc = "Secure Connection Records",

            supportSectionTitle = "Support & Help",
            supportSectionSubtitle = "Fast assistance and guides",
            telegramSupportTitle = "Telegram Support",
            telegramSupportDesc = "24/7 dedicated assistance",
            telegramChannelTitle = "Official Channel",
            telegramChannelDesc = "Server updates & notices",
            officialWebsiteTitle = "Official Website",
            officialWebsiteDesc = "Purchase & renew plan",
            copiedToClipboard = "Copied to clipboard",

            serverStatusTitle = "Server Status",
            statusEncryptedActive = "End-to-end encrypted connection is active",
            statusConnectingToServer = "Connecting to secure server...",
            statusNetworkLostWaiting = "Network lost - Waiting for connection...",
            statusReconnectingAttempt = { attempt -> "Connection dropped - Auto reconnecting (Attempt $attempt)..." },
            statusSubscriptionExpired = "Subscription expired (Connection blocked)",
            statusConnectionError = "Server connection error",
            statusTapToConnect = "Tap button to start secure connection",

            buttonStart = "START",
            buttonConnected = "CONNECTED",
            buttonConnecting = "CONNECTING",
            buttonRetrying = "RETRYING",
            buttonLocked = "LOCKED",
            buttonError = "ERROR",

            durationLabel = "Duration",
            downloadSpeedLabel = "Download",
            uploadSpeedLabel = "Upload",
            remainingDaysLabel = "Days Left",
            totalTrafficLabel = "Total Traffic",
            renewOrStore = "Renew / Store",
            subscriptionExpiredTitle = "Your subscription has expired",
            subscriptionExpiredNotice = "Please renew your plan to reconnect to the secure network.",

            operatorIrancellTag = "Irancell (MTN) • High-Speed VMess",
            operatorRightelTag = "Rightel • High-Speed VMess",
            operatorMciTag = "MCI • Secure SSH Tunnel",
            operatorWifiTag = "Wi-Fi / Other • Secure SSH Tunnel",

            runSpeedTestButton = "Run Speed Test",
            cancelSpeedTestButton = "Stop Test",
            pingLabel = "Ping (Latency)",
            jitterLabel = "Jitter",
            downloadLabel = "Download",
            uploadLabel = "Upload",
            qualityGradeLabel = "Network Grade",

            clearLogsButton = "Clear Logs",
            copyLogsButton = "Copy Logs",
            logsCopiedToast = "Logs copied successfully",
            noLogsAvailable = "No logs recorded yet",

            copyLabel = "Copy",
            helpTipsTitle = "Stable Connection Tips",
            helpTipsBody = "• If speeds are low, please check your mobile operator signal.\n• When switching between Wi-Fi and mobile data, VPN reconnects automatically.\n• All server hosts and credentials are fully encrypted for maximum privacy.",
            speedTestUnit = "Mbps",
            speedTestPing = "Ping",
            speedTestJitter = "Jitter",
            speedTestTunnelStatus = "Tunnel Status",
            speedTestStop = "Stop Speed Test",
            speedTestRetest = "Test Again",
            speedTestStart = "Start Speed Test",
            searchLogsPlaceholder = "Search in logs...",
            filterAll = "All",
            filterErrors = "Errors",
            filterSuccess = "Success",
            filterInfo = "Info",
            noLogsFound = "No logs found.",
            privacyNotice = "All server addresses and credentials are censored for your privacy",
            clearLogsTitle = "Clear Logs History",
            clearLogsConfirm = "Are you sure you want to delete all saved logs?",
            yesDelete = "Yes, Clear",
            logsClearedToast = "Logs cleared successfully",
            openUrlErrorToast = { url -> "Error opening link: $url" },

            // MainScreen Strings
            store = "Store",
            renew = "Renew",
            fastRenew = "Quick Renew",
            subscriptionExpiredNoticeCard = "Your subscription has expired",
            subscriptionExpiredTouchToRenew = "Connection blocked • Tap to renew online",
            subscriptionExpiringDays = { days -> "Only $days days left on your subscription" },
            tunnelConnectingServer = "Connecting to secure server...",
            tunnelInternetDisconnectedWaiting = "Internet disconnected - Waiting for network...",
            tunnelReconnectingAttempt = { attempt -> "Auto-reconnecting (attempt $attempt)..." },
            tunnelReconnecting = "Re-establishing connection tunnel...",
            tunnelErrorTapToRetry = "Connection error - Tap to retry",
            tunnelReadyTapToStart = "Ready to connect - Tap to start",
            standbyWaitingForInternet = "Standby: Waiting for internet connection",
            smartRecoveryActive = { attempt -> "Smart recovery active (attempt $attempt)" },
            connectionDuration = "Connection time:",
            downloadLabelLong = "Download",
            uploadLabelLong = "Upload",
            usernameCard = "Username",
            noAccount = "No account",
            activeSubscription = "Active Subscription",
            expired = "Expired",
            remainingTime = "Remaining Time",
            daysUnit = { days -> "$days days" },
            zeroDays = "0 days",
            urgentRenewNeeded = "Urgent renewal needed",
            validSubscription = "Valid subscription",
            endingSoon = "Expiring soon",
            finishDateSolar = "Expiry Date",
            periodEnd = "End of period",
            jalaliCalendar = "Solar calendar",
            trafficUsage = "Data Usage",
            trafficLimit = { limit -> "Limit: $limit" },
            unlimitedTraffic = "Unlimited data",
            errorOpeningBrowser = "Error opening browser",
            browserErrorWithUrl = { url -> "Error opening browser: $url" },

            // Battery Card
            batteryCardTitle = "Disable Battery Optimization",
            batteryCardSubtitle = "Background stability & low power consumption",
            batteryCardDesc = "Prevents disconnections when screen turns off",
            batteryCardFix = "MTU 1400 Speed Drop Protection",
            batteryCardCpu = "Low CPU Processing",
            batteryCardAndroid = "Compatible with Android 7 to 15",

            // Modal & Voucher Redeem
            subscriptionExpiredTitleModal = "Subscription Expired",
            storeAndRenewTitleModal = "Store & Renewal",
            subscriptionExpiredDescModal = "Your subscription has ended. Please renew with a voucher or buy a new plan from the store.",
            subscriptionActiveDescModal = "Select an option below to purchase or renew with a license code.",
            usernameFieldLabel = "Username:",
            finishDateFieldLabel = "Expiry Date:",
            accountStatusFieldLabel = "Account Status:",
            daysRemainingUnit = { days -> "$days days remaining" },
            renewWithLicenseCode = "Renew with License Code",
            enterStore = "Enter Store",
            recheckAccountStatus = "Check Account Status",
            renewWithVoucherDialogTitle = "Renew with License / Voucher",
            enterVoucherPrompt = "Enter your purchased voucher or license code below to extend your account:",
            activeAccountLabel = "Active Account:",
            voucherExamplePlaceholder = "e.g. GMB-VOUCHER-XXXX",
            clearField = "Clear",
            pasteFromClipboard = "Paste from clipboard",
            dontHaveLicensePrompt = "Don't have a license? Buy instantly from store",
            validatingLicenseOnServer = "Validating license on server...",
            creditAddedDays = { days -> "Added credit: $days days" },
            trafficAddedGB = { gb -> "Added traffic: $gb GB" },
            confirmAndClose = "Confirm & Close",
            renewingProgress = "Renewing...",
            confirmAndRenew = "Confirm & Renew Subscription",
            cancelAction = "Cancel",
            logoutDialogTitle = "Log Out of Account",
            logoutDialogMessage = "Are you sure you want to log out? Logging out will disconnect your active VPN connection.",
            updateTitle = "GMB NET Update",
            updateForceLabel = "Mandatory Update",
            updateVersionLabel = { v -> "Version $v" },
            updateDesc = "A new version of the app has been released with speed and stability improvements.",
            updateChangelogTitle = "What's new in this version:",
            updateDownloadingProgress = "Downloading APK installation file...",
            updateDirectInstall = "Download & Direct Install",
            updateRemindLater = "Remind Me Later",

            // LoginScreen Strings
            loginTitle = "Sign In to App",
            loginSubtitle = "Enter your subscription credentials for secure access",
            loginUsernameLabel = "Username",
            loginUsernamePlaceholder = "Subscription username...",
            loginPasswordLabel = "Password",
            loginPasswordPlaceholder = "Account password...",
            loginRememberMe = "Remember me",
            loginValidating = "Validating & signing in...",
            loginButtonSubmit = "Log In to Account",
            loginOrDivider = "OR",
            loginNeedAccountHint = "Need credentials? Purchase a subscription first",
            loginBuySubscription = "Buy Subscription",
            loginPoweredBy = "Powered by Gambron Net",
            loginValidationEmpty = "Please enter both username and password",

            // PurchaseScreen Strings
            purchaseTitle = "Renew & Purchase with License",
            purchaseSubtitle = "Instant activation and bandwidth top-up",
            back = "Back",
            guestUser = "Guest User",
            remainingCreditLabel = "Remaining Credit",
            remainingTrafficLabel = "Remaining Data",
            expiryDateLabel = "Expiry Date",
            unlimitedLabel = "Unlimited",
            officialWebsiteCard = "Official Website",
            buyVoucherTitle = "Buy Voucher & License Code",
            buyVoucherDesc = "To purchase a license code or renewal voucher, visit our official website. After checkout, enter your code below.",
            goToSiteAndBuy = "Visit gmb-net.ir & buy voucher",
            websiteCopiedToast = "Website address copied",
            copyWebsiteUrl = "Copy website URL",
            instantRechargeCard = "Instant Recharge",
            submitLicenseCard = "Submit License & Activate",
            enterVoucherInBox = "Enter or paste your purchased code below to instantly extend your subscription:",
            licenseInputPlaceholder = "License code (e.g. GMB-VOUCHER-XXXX)",
            communicatingWithServer = "Contacting server & validating license...",
            addedDaysToSubscription = { days -> "+$days days added to your subscription" },
            addedVolumeToAccount = { gb -> "+$gb GB traffic added to your account" },
            checkingAndApplying = "Verifying and applying...",
            confirmAndRenewSubscription = "Confirm & Renew Subscription",
            purchaseStepsTitle = "Steps to Purchase & Renew:",
            step1Number = "1",
            step1Title = "Visit Website gmb-net.ir",
            step1Desc = "Click above to browse plans and purchase your desired subscription.",
            step2Number = "2",
            step2Title = "Receive License / Voucher",
            step2Desc = "After payment, your unique code is delivered instantly on-screen and via email.",
            step3Number = "3",
            step3Title = "Submit Code in App",
            step3Desc = "Enter the code in the box above and tap Confirm to activate immediately."
        )

        val arIq = AppStrings(
            language = AppLanguage.AR_IQ,
            appName = "GMB NET",
            settingsTitle = "الضبط والإعدادات",
            tabSettingsAndAccount = "الحساب والضبط",
            tabSpeedTest = "فحص السرعة",
            tabLogs = "السجلات",
            close = "إغلاق",

            userGreetingDefault = "أهلاً وسهلاً بيك",
            activeGmbAccount = "حساب GMB مفعّل",
            statusConnected = "النت شغال ومحمي",
            statusDisconnected = "مفصول",
            logoutButton = "تسجيل خروج من الحساب",
            logoutDialogTitle = "تسجيل الخروج",
            logoutDialogMessage = "متأكد تريد تسجل خروج من حسابك بالتطبيق؟",
            confirmLogout = "خروج",
            cancel = "إلغاء",

            languageSectionTitle = "لغة التطبيق (Language)",
            languageSectionSubtitle = "اختار اللغة اللي تناسبك لواجهة التطبيق:",
            activeBadge = "شغال",
            langFaTitle = "فارسی",
            langFaDesc = "الفارسية",
            langEnTitle = "English",
            langEnDesc = "الإنكليزية",
            langArIqTitle = "العربية (العراق)",
            langArIqDesc = "عراقي / عربي",

            themeSectionTitle = "المظهر (الوضع الليلي)",
            themeSectionSubtitle = "اختار شكل التطبيق حسب ذوقك (فاتح أو داكن):",
            themeLightTitle = "وضع فاتح",
            themeDarkTitle = "وضع ليلي",
            themeSystemTitle = "تلقائي",
            themeLightBadge = "الفاتح مفعّل",
            themeDarkBadge = "الليلي مفعّل",
            themeSystemBadge = "حسب الجهاز",

            speedTestShortcutTitle = "فحص سرعة النت",
            speedTestShortcutDesc = "البينك والسرعة الحقيقية",
            logsShortcutTitle = "سجلات النظام",
            logsShortcutDesc = "تقارير الاتصال المشفر",

            supportSectionTitle = "الدعم والمساعدة",
            supportSectionSubtitle = "رد سريع وحل المشاكل على مدار الساعة",
            telegramSupportTitle = "دعم التليكرام",
            telegramSupportDesc = "تواصل مباشر ويه الدعم الفني",
            telegramChannelTitle = "قناتنا الرسمية",
            telegramChannelDesc = "آخر التحديثات وأخبار السيرفرات",
            officialWebsiteTitle = "الموقع الرسمي",
            officialWebsiteDesc = "شراء وتجديد الاشتراك",
            copiedToClipboard = "تم النسخ للحافظة",

            serverStatusTitle = "حالة السيرفر",
            statusEncryptedActive = "الاتصال مشفر وآمن وشغال تمام",
            statusConnectingToServer = "جاي يتصل بالسيرفر الآمن...",
            statusNetworkLostWaiting = "انقطع النت - ننتظر رجوع الشبكة...",
            statusReconnectingAttempt = { attempt -> "انفصل الاتصال - جاي يعيد المحاولة تلقائياً (محاولة $attempt)..." },
            statusSubscriptionExpired = "اشتراكك منتهي ومخلص (الاتصال متوقف)",
            statusConnectionError = "صار خلل بالاتصال بالسيرفر",
            statusTapToConnect = "اضغط على الزر حتى تشغل الاتصال الآمن",

            buttonStart = "ابدأ",
            buttonConnected = "متصل",
            buttonConnecting = "جاي يتصل",
            buttonRetrying = "إعادة محاولة",
            buttonLocked = "مقفول",
            buttonError = "خطأ",

            durationLabel = "مدة الاتصال",
            downloadSpeedLabel = "تنزيل (داونلود)",
            uploadSpeedLabel = "رفع (آبلود)",
            remainingDaysLabel = "الأيام الباقية",
            totalTrafficLabel = "حجم البيانات",
            renewOrStore = "تجديد وشراء",
            subscriptionExpiredTitle = "اشتراكك منتهي",
            subscriptionExpiredNotice = "حتى يرجع يشتغل عندك النت المشفر، يرجى تجديد اشتراكك من المتجر.",

            operatorIrancellTag = "إيرانسل (MTN) • بروتوكول VMess السريع",
            operatorRightelTag = "رايتل (Rightel) • بروتوكول VMess السريع",
            operatorMciTag = "همراه أول (MCI) • نفق SSH الآمن",
            operatorWifiTag = "واي فاي / شبكات ثانية • نفق SSH",

            runSpeedTestButton = "ابدأ فحص سرعة النت",
            cancelSpeedTestButton = "إيقاف الفحص",
            pingLabel = "البينك (Ping)",
            jitterLabel = "التذبذب (Jitter)",
            downloadLabel = "الداونلود",
            uploadLabel = "الآبلود",
            qualityGradeLabel = "جودة الخط",

            clearLogsButton = "مسح السجلات",
            copyLogsButton = "نسخ السجلات",
            logsCopiedToast = "تم نسخ السجلات بنجاح",
            noLogsAvailable = "ماكو أي سجلات مسجلة لحد هسه",

            copyLabel = "نسخ",
            helpTipsTitle = "نصائح لثبات الاتصال",
            helpTipsBody = "• إذا لاحظت بطء بالنت، شيك إشارة شبكة موبايلك أول شي.\n• من تحول بين الواي فاي وبيانات الموبايل، الـ VPN راح يعيد الاتصال تلقائياً.\n• كل بيانات السيرفر مشفرة وما تبين لأي شخص لخصوصيتك الكاملة.",
            speedTestUnit = "ميجابت",
            speedTestPing = "البينك (Ping)",
            speedTestJitter = "التذبذب (Jitter)",
            speedTestTunnelStatus = "حالة النفق",
            speedTestStop = "إيقاف فحص السرعة",
            speedTestRetest = "إعادة الفحص",
            speedTestStart = "شروع بفحص السرعة",
            searchLogsPlaceholder = "بحث بالسجلات...",
            filterAll = "الكل",
            filterErrors = "الأخطاء",
            filterSuccess = "الناجحة",
            filterInfo = "معلومات",
            noLogsFound = "ماكو أي سجلات مطابقة.",
            privacyNotice = "كل عناوين وبيانات السيرفر الحساسة مشفرة ومحجوبة لحماية خصوصيتك",
            clearLogsTitle = "مسح سجلات الاتصال",
            clearLogsConfirm = "متأكد تريد تمسح كل السجلات المحفوظة بالجهاز؟",
            yesDelete = "نعم، امسحها",
            logsClearedToast = "تم مسح السجلات بنجاح",
            openUrlErrorToast = { url -> "صار خلل بفتح الرابط: $url" },

            // MainScreen Strings
            store = "المتجر",
            renew = "تجديد",
            fastRenew = "تجديد سريع",
            subscriptionExpiredNoticeCard = "اشتراكك منتهي ومخلص",
            subscriptionExpiredTouchToRenew = "الاتصال متوقف • اضغط للتجديد أونلاين",
            subscriptionExpiringDays = { days -> "باقي بس $days يوم على اشتراكك" },
            tunnelConnectingServer = "جاي يتصل بالسيرفر الآمن...",
            tunnelInternetDisconnectedWaiting = "انقطع النت - ننتظر رجوع الشبكة...",
            tunnelReconnectingAttempt = { attempt -> "جاي يعيد المحاولة تلقائياً (محاولة $attempt)..." },
            tunnelReconnecting = "جاي يعيد بناء نفق الاتصال...",
            tunnelErrorTapToRetry = "صار خلل بالاتصال - اضغط للمحاولة",
            tunnelReadyTapToStart = "جاهز للاتصال - اضغط حتى تبدأ",
            standbyWaitingForInternet = "وضع الانتظار: بانتظار اتصال النت",
            smartRecoveryActive = { attempt -> "الاستعادة الذكية شغالة (محاولة $attempt)" },
            connectionDuration = "وقت الاتصال:",
            downloadLabelLong = "تنزيل (داونلود)",
            uploadLabelLong = "رفع (آبلود)",
            usernameCard = "اسم المستخدم",
            noAccount = "بدون حساب",
            activeSubscription = "اشتراك فعّال",
            expired = "منتهي",
            remainingTime = "الوقت المتبقي",
            daysUnit = { days -> "$days يوم" },
            zeroDays = "0 يوم",
            urgentRenewNeeded = "يحتاج تجديد فوري",
            validSubscription = "اشتراك شغال",
            endingSoon = "قريب يخلص",
            finishDateSolar = "تاريخ الانتهاء",
            periodEnd = "نهاية الفترة",
            jalaliCalendar = "التقويم",
            trafficUsage = "البيانات المستهلكة",
            trafficLimit = { limit -> "الحد: $limit" },
            unlimitedTraffic = "بيانات غير محدودة",
            errorOpeningBrowser = "صار خلل بفتح المتصفح",
            browserErrorWithUrl = { url -> "صار خلل بفتح المتصفح: $url" },

            // Battery Card
            batteryCardTitle = "إلغاء قيود البطارية",
            batteryCardSubtitle = "ثبات بالخلفية واستهلاك خفيف للبطارية",
            batteryCardDesc = "يمنع انقطاع الاتصال من تنطفي الشاشة",
            batteryCardFix = "MTU 1400 لحماية السرعة",
            batteryCardCpu = "معالجة خفيفة على المعالج",
            batteryCardAndroid = "متوافق ويه أندرويد 7 إلى 15",

            // Modal & Voucher Redeem
            subscriptionExpiredTitleModal = "انتهاء صلاحية الاشتراك",
            storeAndRenewTitleModal = "المتجر وتجديد الاشتراك",
            subscriptionExpiredDescModal = "اشتراكك خلص. تكدر تجدده بكود تفعيل أو تشتري من المتجر.",
            subscriptionActiveDescModal = "لشراء اشتراك أو التجديد بكود التفعيل، اختار اللي يعجبك:",
            usernameFieldLabel = "اسم المستخدم:",
            finishDateFieldLabel = "تاريخ الانتهاء:",
            accountStatusFieldLabel = "حالة الحساب:",
            daysRemainingUnit = { days -> "باقي $days يوم" },
            renewWithLicenseCode = "تجديد بكود التفعيل",
            enterStore = "دخول المتجر",
            recheckAccountStatus = "تحديث حالة الحساب",
            renewWithVoucherDialogTitle = "التجديد بكود التفعيل / القسيمة",
            enterVoucherPrompt = "اكتب كود التفعيل أو القسيمة بالمربع جوه حتى يتجدد اشتراكك:",
            activeAccountLabel = "الحساب المفعّل:",
            voucherExamplePlaceholder = "مثال: GMB-VOUCHER-XXXX",
            clearField = "مسح",
            pasteFromClipboard = "لصق من الحافظة",
            dontHaveLicensePrompt = "ما عندك كود؟ اشتري هسة من المتجر",
            validatingLicenseOnServer = "جاي نتأكد من الكود بالسيرفر...",
            creditAddedDays = { days -> "المدة المضافة: $days يوم" },
            trafficAddedGB = { gb -> "البيانات المضافة: $gb كيكابايت" },
            confirmAndClose = "تأكيد وإغلاق",
            renewingProgress = "جاي يجدد...",
            confirmAndRenew = "تأكيد وتجديد الاشتراك",
            cancelAction = "إلغاء",
            logoutDialogTitle = "تسجيل الخروج من الحساب",
            logoutDialogMessage = "متأكد تريد تطلع من الحساب؟ إذا سجلت خروج راح يفصل الاتصال.",
            updateTitle = "تحديث GMB NET",
            updateForceLabel = "تحديث إجباري",
            updateVersionLabel = { v -> "الإصدار $v" },
            updateDesc = "نزل إصدار جديد من التطبيق مع تحسينات بالسرعة والاستقرار.",
            updateChangelogTitle = "التغييرات بهذا الإصدار:",
            updateDownloadingProgress = "جاي ينزل ملف التثبيت APK...",
            updateDirectInstall = "تنزيل وتثبيت مباشر",
            updateRemindLater = "ذكرني بعدين",

            // LoginScreen Strings
            loginTitle = "تسجيل الدخول للتطبيق",
            loginSubtitle = "اكتب معلومات اشتراكك حتى تتصل بأمان",
            loginUsernameLabel = "اسم المستخدم",
            loginUsernamePlaceholder = "اسم المستخدم للاشتراك...",
            loginPasswordLabel = "كلمة المرور",
            loginPasswordPlaceholder = "رمز الحساب...",
            loginRememberMe = "تذكرني",
            loginValidating = "جاي نتأكد ونسجل الدخول...",
            loginButtonSubmit = "تسجيل الدخول",
            loginOrDivider = "أو",
            loginNeedAccountHint = "ما عندك حساب؟ اشتري اشتراك أول شي",
            loginBuySubscription = "شراء اشتراك",
            loginPoweredBy = "مدعوم من كَمبرون نت",
            loginValidationEmpty = "يرجى كتابة اسم المستخدم وكلمة المرور",

            // PurchaseScreen Strings
            purchaseTitle = "التجديد والشراء بكود التفعيل",
            purchaseSubtitle = "تفعيل فوري للمدة والبيانات بالقسيمة",
            back = "رجوع",
            guestUser = "مستخدم ضيف",
            remainingCreditLabel = "المدة المتبقية",
            remainingTrafficLabel = "البيانات المتبقية",
            expiryDateLabel = "تاريخ الانتهاء",
            unlimitedLabel = "غير محدود",
            officialWebsiteCard = "الموقع الرسمي",
            buyVoucherTitle = "شراء كود القسيمة والتفعيل",
            buyVoucherDesc = "حتى تشتري كود تفعيل أو قسيمة تجديد، ادخل على موقعنا الرسمي. بعد الشراء يوصلك الكود وتكدر تدخله بالمربع جوه.",
            goToSiteAndBuy = "الدخول لموقع gmb-net.ir وشراء القسيمة",
            websiteCopiedToast = "تم نسخ رابط الموقع",
            copyWebsiteUrl = "نسخ رابط الموقع",
            instantRechargeCard = "تجديد وشحن فوري",
            submitLicenseCard = "إدخال كود التفعيل والتشغيل",
            enterVoucherInBox = "اكتب أو الصق كود التفعيل أو القسيمة جوه حتى يتجدد اشتراكك فوراً:",
            licenseInputPlaceholder = "كود التفعيل (مثال: GMB-VOUCHER-XXXX)",
            communicatingWithServer = "جاي نتصل بالسيرفر ونتأكد من الكود...",
            addedDaysToSubscription = { days -> "+$days يوم انضافت لاشتراكك" },
            addedVolumeToAccount = { gb -> "+$gb كيكابايت انضافت لحسابك" },
            checkingAndApplying = "جاي الفحص والتطبيق...",
            confirmAndRenewSubscription = "تأكيد وتجديد الاشتراك",
            purchaseStepsTitle = "خطوات الشراء والتجديد:",
            step1Number = "١",
            step1Title = "الدخول لموقع gmb-net.ir",
            step1Desc = "ادخل على الموقع من الزر الفوك واختار الخطة اللي تناسبك واشتريها.",
            step2Number = "٢",
            step2Title = "استلام كود التفعيل / القسيمة",
            step2Desc = "بعد الدفع يوصلك الكود مباشرة بالموقع والإيميل.",
            step3Number = "٣",
            step3Title = "إدخال الكود بالتطبيق",
            step3Desc = "اكتب الكود بالمربع واضغط تأكيد حتى يتفعل حسابك مباشرة."
        )

        fun get(language: AppLanguage): AppStrings {
            return when (language) {
                AppLanguage.FA -> fa
                AppLanguage.EN -> en
                AppLanguage.AR_IQ -> arIq
            }
        }
    }
}

val LocalAppStrings = staticCompositionLocalOf { AppStrings.fa }
